<?php

namespace AppBundle\Repository;

/**
 * ArbitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbitreRepository extends \Doctrine\ORM\EntityRepository
{
}
