<?php

namespace AppBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * ArbitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbitreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    function getActiveFirstQueryBuilder() {
        return $this->createQueryBuilder('arbitre')
        ->orderBy('arbitre.active', 'DESC')
        ->addOrderBy('arbitre.lastName')
        ->addOrderBy('arbitre.firstName');
    }
}
