<?php

namespace AppBundle\Repository;

/**
 * ClassementSaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassementSaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
