<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Competition;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return Competition|null
     */
    public function findOneByName($name) {
        return $this->createQueryBuilder('competition')
            ->where('competition.name LIKE :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return Competition|null
     */
    public function getProLeagueA()
    {
        return $this->findOneByName('Championnat');
    }
}
