<?php

namespace AppBundle\Repository;

/**
 * NationalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByNameQueryBuilder()
    {
        $qb = $this->createQueryBuilder('nationality');
        $qb->orderBy('nationality.name');

        return $qb;
    }
}
