<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Saison;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueryBuilderForPlayerAtSeason(Saison $season){
        $qb = $this->createQueryBuilder('player');
        $qb->leftJoin('player.seasons','seasons')
            ->where($qb->expr()->in('seasons.id',[$season->getId()]))
            ;
        
        return $qb;
    }
}
