<?php

namespace AppBundle\Repository;

/**
 * PlayerVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
