<?php

namespace AppBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    function getActiveFirstQueryBuilder() {
        return $this->createQueryBuilder('season')
            ->orderBy('season.running', 'DESC')
            ->addOrderBy('season.name', 'DESC');
    }
}
