<?php

namespace AppBundle\Repository;

/**
 * TeamCompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamCompetitionRepository extends \Doctrine\ORM\EntityRepository
{
    
}
