<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return null|Team
     */
    public function findOneByName($name)
    {
        return $this->createQueryBuilder('team')
            ->where('team.name LIKE :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
